version: "3.9"

services:
  postgres:
    image: postgres:17
    container_name: what-food-postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: secret
      POSTGRES_DB: fooduserservice
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - what-food-network

  redis:
    image: redis:8-alpine
    container_name: what-food-redis
    restart: always
    ports:
      - "6380:6379"
    networks:
      - what-food-network

  rabbitmq:
    image: rabbitmq:4-management
    container_name: what-food-rabbitmq
    restart: always
    ports:
      - "5673:5672"
      - "15673:15672"
    environment:
      RABBITMQ_DEFAULT_USER: admin
      RABBITMQ_DEFAULT_PASS: secret
    networks:
      - what-food-network

  user-service:
    image: gopherkhb/what-food-user-service:latest
    container_name: what-food-user-service
    restart: always
    env_file:
      - ./user-service/.env
    depends_on:
      - postgres
      - redis
      - rabbitmq
    networks:
      - what-food-network

  user-product-service:
    image: gopherkhb/what-food-user-product-service:latest
    container_name: what-food-user-product-service
    restart: always
    env_file:
      - ./user-product-service/.env
    depends_on:
      - postgres
      - redis
      - rabbitmq
    networks:
      - what-food-network

volumes:
  postgres_data:

networks:
  what-food-network:
    driver: bridge